In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
# Load the dataset of Walmart sales
Data_raw = pd.read_csv('/Users/saikatgayen/WORKSPACE/Dynamic Pricing and Inventory Forcasting System/data/raw/Walmart_Sales.csv')
Data_raw.head()

,Store,Date,Weekly_Sales,Holiday_Flag,Temperature,Fuel_Price,CPI,Unemployment
0,1,05-02-2010,1643690.90,0,42.31,2.572,211.096358,8.106
1,1,12-02-2010,1641957.44,1,38.51,2.548,211.242170,8.106
2,1,19-02-2010,1611968.17,0,39.93,2.514,211.289143,8.106
3,1,26-02-2010,1409727.59,0,46.63,2.561,211.319643,8.106
4,1,05-03-2010,1554806.68,0,46.50,2.625,211.350143,8.106

In [7]:
# Load the dataset of competitor prices
Data_compi = pd.read_csv('/Users/saikatgayen/WORKSPACE/Dynamic Pricing and Inventory Forcasting System/data/external/competitor_prices.csv')
Data_compi.head()

,Product_Name,Current_Price,Rating,Timestamp
0,bb Royal\nSona Masoori Rice/Akki Raw Rice/Akki...,₹599.00,Shop by,2026-04-27 13:38:56.661806
1,Sona Masoori Rice/Akki Raw Rice/Akki - Super P...,₹1000.00,Category,2026-04-27 13:38:56.661806
2,Daawat\nRozana Super Basmati Rice\n3.8\n17868 ...,₹70.50,Select Location,2026-04-27 13:38:56.661806
3,Rozana Super Basmati Rice,₹100.00,Select Location,2026-04-27 13:38:56.661806
4,bb Popular\nSona Masoori New Pongal Rice\n5 kg,₹331.00,Select Location,2026-04-27 13:38:56.661806

## Feature Enginnering

In [ ]:
# 1. Convert the 'Date' column to Datetime objects
# The Walmart dataset usually uses DD-MM-YYYY format, so we specify the format accordingly

Data_raw['Date'] = pd.to_datetime(Data_raw['Date'], dayfirst=True)

# 2. Extract basic 'Date' components: Day, Month, Year
Data_raw['Day'] = Data_raw['Date'].dt.day
Data_raw['Month'] = Data_raw['Date'].dt.month
Data_raw['Year'] = Data_raw['Date'].dt.year

# 3. Extract calender-spedific features
Data_raw['week_of_year'] = Data_raw['Date'].dt.isocalendar().week
Data_raw['day_of_week'] = Data_raw['Date'].dt.dayofweek
Data_raw['quarter'] = Data_raw['Date'].dt.quarter

# 4. create the 'is_weekend' flag (1 for Saturday and Sunday, 0 for weekdays)
Data_raw['is_weekend'] = Data_raw['day_of_week'].apply(lambda x: 1 if x >= 5 else 0)

# 5. Create the 'season' feature
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Fall'
    
Data_raw['season'] = Data_raw['Month'].apply(get_season)

# Display the results
print(Data_raw[['Date', 'Day', 'Month', 'Year', 'week_of_year', 'day_of_week', 'quarter', 'is_weekend', 'season']].head())